### ISSUE TITLE
Some experiments

### ISSUE THREAD

**Issue by shanemikel** [openSUSE/artwork#18]
I'm no artist, but here's some stuff I managed to do with some amazing GIMP filters.  The background texture is from this repo.

http://imgur.com/a/3QF18

**Comment by shanemikel** [comment]
I'd like it if somebody could figure out how to use GIMP's weave filter (combined with some others, no doubt) to better achieve the low-res display effect I was going for in one of those.

Also, I'd really like it if you'd continue to package the background textures, and logo separately (perhaps by default using the lone background texture as the lock/login screen backgrounds, and the logo version as a default wallpaper).  Things like that give the effect of cohesive branding.

**Comment by javierllorente** [comment]
Hi shanemikel,
We usually talk about our experiments in the artwork mailing list.
http://lists.opensuse.org/opensuse-artwork/
Please subscribe and share your ideas there :)
Thanks!
Javier
