### ISSUE TITLE
some files not available with cloning...

### ISSUE THREAD

**Issue by Dutchglory** [openSUSE/artwork#24]
some files not available with cloning...

Cloning into 'OPENSUSE-ARTWORK-GIT'...
remote: Counting objects: 8680, done.
remote: Compressing objects: 100% (10/10), done.
emote: Total 8680 (delta 3), reused 0 (delta 0), pack-reused 8670
Receiving objects: 100% (8680/8680), 4.83 GiB | 4.20 MiB/s, done.
Resolving deltas: 100% (4738/4738), done.
Checking connectivity... done.
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 11:11:12.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 11:11:31.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 11:12:40.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 11:13:13.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 11:13:44.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 11:22:33.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 11:25:00.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 11:33:30.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 11:43:04.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 11:43:40.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 11:43:54.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 11:47:59.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 11:48:03.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 11:48:09.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 11:48:16.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 11:48:27.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 11:48:34.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 11:48:36.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 11:48:37.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 11:48:39.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 11:52:24.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 12:03:58.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 12:04:12.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 12:09:15.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 12:13:29.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 12:14:00.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/GNOME/Screenshot from 2013-02-07 12:14:07.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/LXDE/Screenshot from 2013-02-09 12:45:42.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/LXDE/Screenshot from 2013-02-09 12:46:13.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/LXDE/Screenshot from 2013-02-09 12:46:40.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/LXDE/Screenshot from 2013-02-09 12:47:39.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/LXDE/Screenshot from 2013-02-09 12:48:25.png (Invalid argument)
error: unable to create file Marketing Materials/Screenshots/12.3/LXDE/Screenshot from 2013-02-09 12:48:53.png (Invalid argument)
Checking out files: 100% (2684/2684), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by cho2** [comment]
![cuplikan layar dari 2017-01-29 13-29-33](https://cloud.githubusercontent.com/assets/6271071/22402362/013c0cde-e627-11e6-9260-250cae0383da.png)

I think the problem is the file name that containing ":"

**Comment by Dutchglory** [comment]
i guess its a Windows thing....

**Comment by coolo** [comment]
you cant' have : in filenames on windows

**Comment by tigerfoot** [comment]
Since then I guess you've moved to one of our flagship distribution Leap or Tumbleweed.
To be precise, you can't have : char on ntfs, and or smb protocol.
