### ISSUE TITLE
Make relevant branding more visible

### ISSUE THREAD

**Issue by hellcp** [openSUSE/artwork#29]
This repository is very confusing to use, finding anything is really hard, unless you know where it is, or you put it there before.

I suggest more streamlined approach, categorical one, which would highlight stuff that is compatible with our current branding guidelines.

.
├── Banners
│   ├── Print
│   └── Web
│       └── Old
│           └── 13.1
├── Box_Design
├── Flyers
│   └── Old
├── Fonts
│   ├── Old
│   │   └── FifthLeg
│   ├── OpenSans
│   └── SourceSansPro
├── Logos
│   ├── Buttons
│   ├── Events
│   ├── Leap
│   ├── Official
│   ├── Proposals
│   └── Tumbleweed
├── Merch
│   ├── Cheat_Cubes
│   ├── Keychain
│   ├── Magazine
│   ├── Mugs
│   └── T-Shirts
├── Misc
│   ├── Business_Cards
│   ├── CD_Sleeves
│   ├── Letterheads
│   └── Screenshots
├── Posters
│   └── Old
│       └── oSC13
├── Slides
│   ├── Old
│   │   └── 12.1
│   │       ├── 12.1-GNOME3.odp
│   │       ├── 12.1 introduction-to-suse-studio 30min.odp
│   │       ├── 12.1 OBS-Fosscomm2012.el.odp
│   │       └── 12.1 OBS-Fosscomm2012.en.odp
│   ├── openSUSE 2015 Template - Dark.odp
│   ├── openSUSE 2015 Template.odp
│   ├── openSUSE Template 2017 - Wide.odp
│   └── openSUSE Template 2018 - Wide-2.odp
├── Stickers
│   └── Old
├── Teams
├── Videos
│   └── Old
└── Wallpapers
    └── Old

Where Slides is perfect example of the structure. Majority of stuff would be in main directory to have it easily accessible. All the stuff that is no longer relevant (due to being from old release or event or not being made in current branding guidelines) would be in Old directory.

What do you think?

**Comment by hellcp** [comment]
CC @ddemaio @sysrich @tigerfoot as you seem to use this repo the most ;)

**Comment by simotek** [comment]
the alternative would be putting everything old in _old_ at the top level
then recreating the structure in there

**Comment by hellcp** [comment]
That would be annoying when moving stuff over between releases/events or simply retiring old artwork

**Comment by tigerfoot** [comment]
It is up to people that want to contribute to this repository to organize it.
Beware, sometimes there's links outside pointing to material here (most I guess in the wiki).

You're proposed tree doesn't make it clear in all cases for example what  Merch could be
 Merchandising, then why Stickers is not in ? ;-) 

If you thinks that there's too much oldies, I agree with @simotek better to move oldies in oldies (if possible by version (distribution related) or years (for others like events and so).

Also perhaps it is time to split it into git submodules ?

**Comment by hellcp** [comment]
That's what I wanted to do for some time, just wanted to ask to not do something against somebody else's will ;)

Oh, whoops, missed the stickers

It might be the time to create submodules, this repo's pack is 5GB in size (which is compressed value). And in the past it was used for completely different thing. Bunch of stuff from gitorious got lost in transit into this repo, and some stuff was outright removed :/

**Comment by hellcp** [comment]
I moved old stuff into ["archival" branch](https://github.com/openSUSE/artwork/tree/archival), if anybody is looking for it, the master was reset to first commit, so downloading just master isn't over 5GB of data anymore.
