### ISSUE TITLE
Tumbleweed icon

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/artwork#38]
The tumbleweed icon has very thin stroke. Compared to the solid leap icon, it looks very thin and short.

![image](https://user-images.githubusercontent.com/5836790/75106586-f2c58b80-5626-11ea-9793-8c53ca35fb30.png)

How about make it something round/square? The following icon is a good example, look like a real tumbleweed plant.

![image](https://user-images.githubusercontent.com/5836790/75106648-77b0a500-5627-11ea-8494-782066b9cd5f.png)

**Comment by hellcp** [comment]
New Tumbleweed logo will have to be decided together with the new project logo in openSUSE/branding#93

**Comment by lkocman** [comment]
let me close the issue.
