### ISSUE TITLE
repository still seems to have a lot of small files checkout took almost 40minutes

### ISSUE THREAD

**Issue by lkocman** [openSUSE/artwork#39]
lkocman@linux:~/Workspace/opensuse> git clone git@github.com:openSUSE/artwork.git
Cloning into 'artwork'...
remote: Enumerating objects: 9214, done.
remote: Total 9214 (delta 0), reused 0 (delta 0), pack-reused 9214
Receiving objects: 100% (9214/9214), 4.89 GiB | 3.16 MiB/s, done.
Resolving deltas: 100% (4976/4976), done.

Initial 40% were really slow, rest was done like in 5 minutes. So something tells me that first 4 GiB of the repository deserves a proper cleanup.

**Comment by hellcp** [comment]
Please use --single-branch

**Comment by vinzv** [comment]
`--single-branch` took <20 seconds. Let's close this issue.
