### ISSUE TITLE
unable to clone master branch with git ....

### ISSUE THREAD

**Issue by Dutchglory** [openSUSE/artwork#45]
command:
_git clone https://github.com/openSUSE/artwork.git OPENSUSE-Artwork-github_

output:
_remote: Enumerating objects: 58, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 9272 (delta 8), reused 0 (delta 0), pack-reused 9214
Receiving objects: 100% (9272/9272), 4.96 GiB | 27.65 MiB/s, done.
Resolving deltas: 100% (4984/4984), done.
error: invalid path 'slides/openSUSE-template-greenhex/asset-16:9/odg/object.odg'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'_

**Comment by ddemaio** [comment]
@Dutchglory could you try now.

**Comment by vinzv** [comment]
Works for me:
```
$ git clone https://github.com/openSUSE/artwork.git OPENSUSE-Artwork-github
Klone nach 'OPENSUSE-Artwork-github' ...
remote: Enumerating objects: 112, done.
remote: Counting objects: 100% (112/112), done.
remote: Compressing objects: 100% (97/97), done.
remote: Total 9326 (delta 35), reused 38 (delta 15), pack-reused 9214
Empfange Objekte: 100% (9326/9326), 4.96 GiB | 11.93 MiB/s, Fertig.
Löse Unterschiede auf: 100% (5011/5011), Fertig.

```

Let's close this issue unless @Dutchglory comes back with still existing problems.
