### ISSUE TITLE
Designs for openSUSE swag for this year

### ISSUE THREAD

**Issue by kstreitova** [openSUSE/artwork#55]
Hello,

Every year, we create some new openSUSE swag that we then use at conferences, openSUSE booths, university job fairs and other events in the Czech Republic. For this year, we would like to create something new, not just putting openSUSE chameleon or Alex on the T-Shirt. I was told that the openSUSE Artwork group could help us with that.

So I would like to open this issue as a kind request for your designs for our merch for this year. It would be great to have something cool and special or something with a story behind it (e.g. I think that the T-Shirts "Release is coming" were pretty popular).

We can collect your ideas for few weeks and select the best one in the end. I hope that there will be a lot of interesting ideas. And if not, in the worst case, we can always use the good old Geeko :)

What do you think about it?

**Comment by ddemaio** [comment]
Hi @kstreitova. It would be great to have something new. I'll bring it up as a topic to discuss in our community meeting. Maybe a refresh of the cheetsheet would be nice. Would also do something like a winter cap or something. I'll see what we can come up with.

**Comment by kstreitova** [comment]
Maybe I was too vague with using the word "design" :) We are basically looking for graphics/logos that we can use for T-Shirts (and possibly for other merch).

**Comment by ddemaio** [comment]
We have some new branding images were a looking at testing out. We also have the rainbow one and group that hangs out in the openSUSE bar are thinking of having a t-shirt or something. There might be someone here that can make something. Do you have any ideas or visuals you have in mind? 
![bar](https://user-images.githubusercontent.com/8996626/131854023-cbcd5531-e9c6-4eed-9c0c-2774ff227b50.png)
![kubicwords](https://user-images.githubusercontent.com/8996626/131853451-65d4c433-7743-4bb3-87b1-adae09c22c8c.png)
![leap](https://user-images.githubusercontent.com/8996626/131853474-8e01cb1d-13bf-4068-817f-24d14be428dc.png)
![microos](https://user-images.githubusercontent.com/8996626/131853494-102abe2d-8ba0-42f0-ae55-0b356eb37aae.png)
![tumbleweed](https://user-images.githubusercontent.com/8996626/131853542-06334d24-be93-4963-8911-8b5348825a40.png)
![openSUSE-rainbow-bg](https://user-images.githubusercontent.com/8996626/131853566-15aa2084-f832-4e60-b6c6-c38223a79ebb.png)

**Comment by ddemaio** [comment]
Here is a list of things we came up with @kstreitova - https://etherpad.opensuse.org/p/weeklymeeting20210902

**Comment by kstreitova** [comment]
I'm closing this issue as it's no longer relevant. Thanks, @ddemaio for all these ideas and for actually creating the logo we used in the end.
